arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: false
printWidth: 120
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: false
tabWidth: 2
trailingComma: none
useTabs: false

overrides:
- files: "*.json"
  options:
    printWidth: 200