// Claims
export const CLAIMS_DATA = "CLAIMS_DATA";
export const GET_CLAIMS = "GET_CLAIMS";

// Slide Tracking
export const SET_CLIENT_COURSE_STATE = "SET_CLIENT_COURSE_STATE";
export const GET_COURSE_STATE = "GET_COURSE_STATE";
export const SET_SERVER_LAST_SLIDE = "SET_SERVER_LAST_SLIDE";
export const ADD_CLIENT_SLIDES_VISITED = "ADD_CLIENT_SLIDES_VISITED";
export const ADD_CLIENT_QUIZ_SCORE = "ADD_CLIENT_QUIZ_SCORE";
export const REMOVE_CLIENT_QUIZ_SCORE = "REMOVE_CLIENT_QUIZ_SCORE";

// Other Course State
export const SET_SERVER_MUTE_ON = "SET_SERVER_MUTE_ON";
export const SET_SERVER_AUTO_ADVANCE = "SET_SERVER_AUTO_ADVANCE";
export const SET_SERVER_QUIZ_SCORE = "SET_SERVER_QUIZ_SCORE";

// Tracking tabs
export const NAVIGATE_TO_TAB = "NAVIGATE_TO_TAB";

// Fetching/setting TOC Data
export const GET_TOC_DATA = "GET_TOC_DATA";
export const SET_CLIENT_TOC_DATA = "SET_CLIENT_TOC_DATA";

// Errors
export const SET_ERROR = "SET_ERROR";

//QT Full Screen
export const ENTER_FULLSCREEN = "ENTER_FULLSCREEN";
export const EXIT_FULLSCREEN = "EXIT_FULLSCREEN";

//Load TOC
export const FLAG_TOC_DISPLAYED = "FLAG_TOC_DISPLAYED";

// User Progress
export const GET_USER_PROGRESS = "GET_USER_PROGRESS";
export const SET_CLIENT_USER_PROGRESS = "SET_CLIENT_USER_PROGRESS";
export const SET_SERVER_USER_PROGRESS_PERCENT_COMPLETE = "SET_SERVER_USER_PROGRESS_PERCENT_COMPLETE";

// Captivate Initialization
export const IFRAME_DATA_INITIALIZED = "IFRAME_DATA_INITIALIZED";

// Test Data Actions
export const TEST_INCREMENT_INDEX = "TEST_INCREMENT_INDEX";
export const TEST_DECREMENT_INDEX = "TEST_DECREMENT_INDEX";
